# Generated by Django 2.0.6 on 2018-06-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='prof',
            field=models.CharField(default='Steven Halim', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
