# Generated by Django 2.0.6 on 2018-06-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20180612_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='module',
            field=models.CharField(max_length=30),
        ),
    ]
