# Generated by Django 2.0.6 on 2018-06-12 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20180612_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='prof',
        ),
    ]
