# Generated by Django 2.0.6 on 2018-06-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_tutorial_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='prof',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
