# Generated by Django 2.0.6 on 2018-06-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_tutorial_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='prof',
            field=models.CharField(max_length=30),
        ),
    ]
