# Generated by Django 2.0.6 on 2018-06-13 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20180612_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_of',
            new_name='tutorials',
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='tutorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Tutorial'),
        ),
    ]
