# Generated by Django 2.0.6 on 2018-06-14 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20180613_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='tutorial',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='prof',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
