# Generated by Django 2.0.6 on 2018-06-14 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_auto_20180614_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='tutorialgroup',
            new_name='group',
        ),
    ]
