# Generated by Django 2.0.6 on 2018-06-14 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_auto_20180614_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Tutorial')),
            ],
        ),
    ]
