# Generated by Django 2.0.6 on 2018-06-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='session',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
