# Generated by Django 2.0.6 on 2018-06-28 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_student_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='image',
            field=models.ImageField(default='default.png', upload_to='session_image'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profilepic',
            field=models.ImageField(default='default.png', upload_to='profile'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Session'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Student'),
        ),
    ]
