# Generated by Django 2.0.6 on 2018-06-28 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_auto_20180628_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
