# Generated by Django 2.0.6 on 2018-06-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
